#!/usr/bin/env python

from waflib.extras import symwaf2ic
from waflib import Utils

def depends(dep):
    pass

def options(opt):
    pass

def configure(cfg):
    pass

def build(bld):
    bld.install_files(
        '${PREFIX}/lib',
        bld.path.ant_glob('roqt/**/*.py'),
        relative_trick=True,
    )
    bld.install_files(
        '${PREFIX}/bin',
        'bin/roqt',
        relative_trick=False,
        chmod=Utils.O755,
    )
