#!/usr/bin/env python
import sys, os

def depends(dep):
    dep('marocco')
    dep('marocco', 'pymarocco')


def options(opt):
    opt.load('compiler_cxx')
    opt.load('gtest')
    opt.load('pytest')


def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('gtest')
    cfg.load('pytest')


def build(bld):

    bld(target          = 'test-marocco',
        features        = 'cxx cxxprogram gtest',
        test_main       = 'main.cpp',
        source          = bld.path.ant_glob('**/test-*.cpp', excl=['coordinates/**/*']),
        install_path    = os.path.join('bin', 'tests'),
        test_timeout    = 60,
        use             = [
            'marocco',
            'sthal',
            ],
        )

    bld(target='test-marocco_coordinates',
        features='cxx cxxprogram gtest',
        source=bld.path.ant_glob('coordinates/test-*.cpp'),
        install_path='bin/tests',
        use=[
            'marocco_coordinates',
        ]
    )

    bld(target='marocco_coordinates-pytest',
        features='pytest',
        tests=bld.path.ant_glob('coordinates/test-*.py'),
        install_path='bin/tests',
        use=[
            'pyhalbe',
            'pymarocco_coordinates',
        ])

    bld(target='marocco-pytest-quick',
        features='pytest',
        tests=bld.path.ant_glob('python/quick/test*.py'),
        test_timeout=60,
        use=['pyhmf', 'pymarocco_scripts', 'pysthal_test_dep', 'pymarocco_runtime'],
        test_environ    = {
            'MAROCCO_VERSION_DATADIR': bld.env.MAROCCO_VERSION_DATADIR
        })

    bld(target='marocco-pytest-slow',
        features='pytest',
        tests=bld.path.ant_glob('python/slow/test*.py'),
        test_timeout=180,
        use=['pyhmf', 'pymarocco_scripts', 'pysthal_test_dep', 'pymarocco_runtime'],
        test_environ    = {
            'MAROCCO_VERSION_DATADIR': bld.env.MAROCCO_VERSION_DATADIR
        })

    from waflib.extras.gtest import summary
    bld.add_post_fun(summary)
