#!/usr/bin/env python
import sys, os

from waflib import Options

def options(opt):
    opt.load('compiler_c')

def configure(cfg):
    cfg.load('compiler_c')

    cfg.check_cc(
            msg = "Checking for 'libm'",
            lib='m',
            uselib_store='LIBM')


    cfg.env.INCLUDES_GKLIBUSE = [
        cfg.path.find_dir('GKlib').abspath()
    ]
    cfg.env.CFLAGS_GKLIBUSE   = [
            '-O3',
            '-std=c99',
            '-fno-strict-aliasing',
            '-DLINUX',
            '-D_FILE_OFFSET_BITS=64',
            '-Werror',

            # various debugging stuff
            #'-g',
            #'-DDEBUG',
            #'-DNDEBUG',
            #'-DNDEBUG2',

            # OpenMP Support
            #'-D__OPENMP__',
        ]

    cfg.env.INCLUDES_METISUSE = [
        cfg.path.find_dir(xx).abspath() for xx in ['libmetis', 'include']
    ]
    cfg.env.CFLAGS_METISUSE   = [
            '-g',
            '-O1',
        ]

def build(bld):

    bld.shlib(
        target          = 'GKlib',
        source          = bld.path.ant_glob('GKlib/*.c'),
        install_path    = 'lib',
        export_includes = bld.env.INCLUDES_GKLIBUSE,
        use             = ['GKLIBUSE',],
    )

    bld.shlib(
        target          = 'metis',
        source          = bld.path.ant_glob('libmetis/*.c'),
        install_path    = 'lib',
        export_includes = 'include',
        use             = ['METISUSE', 'GKlib', 'LIBM'],
    )
