import os
from waflib import Node


def options(opt):
    pass


def configure(conf):
    env = conf.env
    conf.setenv('marocco_webvisu')
    blddir_webvisu = conf.path.get_bld()
    Node.Node.mkdir(blddir_webvisu)
    conf.env.NODE_HOME = '{}/node_home'.format(blddir_webvisu)
    conf.env.PATH = '{}/node_modules/.bin:{}'.format(blddir_webvisu, os.environ['PATH'])
    conf.find_program('npm')
    conf.setenv('', env=env)


def build(bld):
    bld.env = bld.all_envs['marocco_webvisu']
    srcdir_webvisu = bld.path.get_src()
    blddir_webvisu = bld.path.get_bld()

    # we copy ts sources to the waf build folder
    cp_cmd = "cp -a {srcdir} {blddir}".format(srcdir=srcdir_webvisu, blddir=blddir_webvisu)
    bld.cmd_and_log (cp_cmd)

    # use npm to acquire all the ts module dependencies
    npm_cmd = "HOME={home} {npm} {{}}".format(home=bld.env.NODE_HOME, npm=bld.env.NPM[0])
    bld.cmd_and_log (npm_cmd.format('install'), cwd=blddir_webvisu.find_dir('webvisu'))

    # and run a npm script which builds and installs the static assets
    bld.cmd_and_log (npm_cmd.format('run prepare'), cwd=blddir_webvisu.find_dir('webvisu'))

    # use waf for installing to target folder
    dist_folder = blddir_webvisu.find_dir('webvisu').find_dir('dist')
    bld.install_files('${PREFIX}/lib/webvisu', dist_folder.ant_glob('**/*'), cwd=dist_folder, relative_trick=True)

    bld.env = bld.all_envs['']
