#!/usr/bin/env python
import sys, os

def options(opt):
    opt.load('compiler_cxx')

def configure(cfg):
    cfg.load('compiler_cxx')

def build(bld):
    bld(target          = 'nanoflann_inc',
        export_includes = './current')
